# https://docs.github.com/ja/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
    time: "08:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
  assignees:
    - nothink
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "08:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
  assignees:
    - nothink
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
    time: "08:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10
  assignees:
    - nothink
