version: '3.9'

services:
  app:
    build: .
    image: momoichigo:dev
    container_name: app
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./.env:/app/.env
      - ./cred.json:/cred.json
    environment:
      DEV: TRUE
      GOOGLE_APPLICATION_CREDENTIALS: /cred.json
    links:
      - db:db

  db:
    image: postgres:alpine
    container_name: db
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: momoichigo
      POSTGRES_USER: momoichigo
      POSTGRES_PASSWORD: momoichigo

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
