# Generated by Django 3.2.6 on 2021-08-05 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.URLField(
                        max_length=1024,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="This url isn't a valid url of the 'vcard' resources",
                                regex="^http(s)?://dqx9mbrpz1jhx.cloudfront.net/vcard/.*",
                            )
                        ],
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
