# Generated by Django 3.2.7 on 2021-09-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(max_length=1024, upload_to=''),
        ),
    ]
