# Generated by Django 3.2.7 on 2021-09-30 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='source',
            field=models.URLField(db_index=True, max_length=1024, unique=True, validators=[django.core.validators.RegexValidator(message="This url isn't a valid url of the 'vcard' resources", regex='^http(s)?://dqx9mbrpz1jhx.cloudfront.net/vcard/.*')]),
        ),
        migrations.AlterField(
            model_name='resourcequeue',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resource', unique=True),
        ),
    ]
