# Generated by Django 3.2.7 on 2021-10-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210930_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcequeue',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.resource'),
        ),
    ]
