# Generated by Django 3.2.7 on 2021-10-07 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_resourcequeue_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcequeue',
            name='created',
        ),
        migrations.RemoveField(
            model_name='resourcequeue',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='resourcequeue',
            name='resource',
        ),
        migrations.AddField(
            model_name='resourcequeue',
            name='source',
            field=models.URLField(default='https://vcard.ameba.jp/', max_length=1024),
            preserve_default=False,
        ),
    ]
