name: Build Image

on:
  push:
    branches: [main]

env:
  # Name of Docker images
  USER_NAME: nothink
  IMAGE_NAME: momoichigo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.in-project true

      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: v0.0.0

      - name: Get Timestamp
        uses: nanzm/get-time-action@v1.1
        id: timestamp
        with:
          timeZone: 9
          format: 'YYYYMMDDHHmmss'

      - name: Get Current Version
        id: current_version
        run: |
          current=$(poetry version -s)
          echo ${current}
          echo ::set-output name=VERSION::${current}

      - name: Check that version is bumped
        id: version_is_bumped
        run: |
          pip install semver
          compare=`python -c "import semver; print(semver.compare('${{ steps.current_version.outputs.VERSION }}', '${{ steps.previoustag.outputs.tag }}'[1:]))"`
          echo ${compare}
          echo ::set-output name=COMPARE::${compare}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Version is bumped
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          tag: v${{ steps.current_version.outputs.VERSION }}

      - name: Build and Push Image
        if: ${{ steps.version_is_bumped.outputs.COMPARE == '1' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.current_version.outputs.VERSION }}

      - name: Create Release
        if: ${{ steps.version_is_bumped.outputs.COMPARE == '1' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.current_version.outputs.VERSION }}
          release_name: v${{ steps.current_version.outputs.VERSION }}
          draft: false
          prerelease: false

      # Version is not bumped
      - name: Build and Push Image
        if: ${{ steps.version_is_bumped.outputs.COMPARE == '0' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.current_version.outputs.VERSION }}-${{ steps.timestamp.outputs.time }}
