name: 'Flake8'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DEBUG: true
  TZ: Asia/Tokyo
  RUNTIME: local

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      - uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Run Lint using Flake8
        run: poetry run flake8
