name: 'Hadolint'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DEBUG: true
  TZ: Asia/Tokyo
  RUNTIME: local

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v1.7.0
        with:
          dockerfile: Dockerfile
          ignore: DL3009 DL3042 
